services:
  users-db:
    image: mongo
    container_name: users-db
    ports:
      - "27017:27017"
    volumes:
      - users-db_data:/data/db
  farms-db:
    image: mongo
    container_name: farms-db
    ports:
      - "27018:27017"
    volumes:
      - farms-db_data:/data/db
      - ./backend/seeds.json:/data/seeds.json
      - ./backend/init-farms.sh:/docker-entrypoint-initdb.d/init-farms.sh
  seeds-db:
    image: mongo
    container_name: seeds-db
    ports:
      - "27019:27017"
    volumes:
      - ./backend/seeds.json:/data/seeds.json
      - ./backend/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  notifications-db:
    image: mongo
    container_name: notifications-db
    ports:
      - "27020:27017"
    volumes:
      - notifications-db_data:/data/db

  # Eureka Service Registry
  service-registry:
    build: ./backend/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/

  # User Service
  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8081:8081"
      - "5005:5005"   # expose debug port to host
    depends_on:
      service-registry:
        condition: service_started
      users-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - spring.profiles.active=prod
      - spring.data.mongodb.uri=mongodb://users-db:27017/usersdb
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  # Farm Service
  farm-service:
    build: ./backend/farm-service
    container_name: farm-service
    ports:
      - "8082:8082"
      - "5006:5006"   # expose debug port to host
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      seeds-db:
        condition: service_started
      farms-db:
        condition: service_started
      user-service:
        condition: service_started
    environment:
      - spring.profiles.active=prod
      - spring.data.mongodb.uri=mongodb://farms-db:27017/farmsdb
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - user-service
      - farm-service
    environment:
      - spring.profiles.active=prod
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/

  # Rule Engine Service
  rule-engine:
    build: ./backend/rule-engine
    container_name: rule-engine
    ports:
      - "8084:8084"
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      seeds-db:
        condition: service_started
      notification-service:
        condition: service_started
      farm-service:
        condition: service_started
    environment:
      - spring.profiles.active=prod
      - spring.data.mongodb.uri=mongodb://seeds-db:27017/seedsdb
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      notifications-db:
        condition: service_started
    environment:
      - spring.profiles.active=prod
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - spring.data.mongodb.uri=mongodb://notifications-db:27017/notificationsdb
      - spring.data.mongodb.auto-index-creation=true

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672

      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=aagriscope@gmail.com
      - SPRING_MAIL_PASSWORD=ftnxrgeryqkzgjzq
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  sensor-ingestion-service:
    build: ./backend/sensor-ingestion-service
    container_name: sensor-ingestion
    depends_on:
      rabbitmq:
          condition: service_healthy
      users-db:
        condition: service_started
      farms-db:
        condition: service_started
      rule-engine:
        condition: service_started

    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - USERS_MONGO_URI=mongodb://users-db:27017/usersdb
      - FARMS_MONGO_URI=mongodb://farms-db:27017/farmsdb


volumes:
  users-db_data:
  farms-db_data:
  notifications-db_data:
