services:
  users-db:
    image: mongo
    container_name: users-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - users-db_data:/data/db
  farms-db:
    image: mongo
    container_name: farms-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - farms-db_data:/data/db
      - ./backend/seeds.json:/data/seeds.json
      - ./backend/init-farms.sh:/docker-entrypoint-initdb.d/init-farms.sh
  seeds-db:
    image: mongo
    container_name: seeds-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./backend/seeds.json:/data/seeds.json
      - ./backend/init-seeds.sh:/docker-entrypoint-initdb.d/init-seeds.sh

  notifications-db:
    image: mongo
    container_name: notifications-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - notifications-db_data:/data/db

  # Eureka Service Registry
  service-registry:
    build: ./backend/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - eureka.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/

  # User Service
  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      service-registry:
        condition: service_started
      users-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@users-db:27017/usersdb?authSource=admin
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - APP_FRONTEND_URL=http://bauerblick.com
      - ALLOWED_ORIGIN=http://bauerblick.com

  # Farm Service
  farm-service:
    build: ./backend/farm-service
    container_name: farm-service
    ports:
      - "8082:8082"
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      seeds-db:
        condition: service_started
      farms-db:
        condition: service_started
      user-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=farms-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=farmsdb
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - API_GATEWAY_URL=http://api-gateway:8080
      - ALLOWED_ORIGIN=http://bauerblick.com

  # API Gateway
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - user-service
      - farm-service
    environment:
      - spring.profiles.active=prod
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - EUREKA_SERVER=http://service-registry:8761/eureka/

  # Rule Engine Service
  rule-engine:
    build: ./backend/rule-engine
    container_name: rule-engine
    ports:
      - "8084:8084"
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      seeds-db:
        condition: service_started
      notification-service:
        condition: service_started
      farm-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=seeds-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=seedsdb
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - FARM_SERVICE_URL=http://api-gateway:8080/api/farms
      - ALLOWED_ORIGIN=http://bauerblick.com

  # Notification Service
  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      service-registry:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      notifications-db:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=notifications-db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=notificationsdb
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_USER}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_PASSWORD}
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_MAIL_HOST=smtp.zoho.eu
      - SPRING_MAIL_PORT=587
      - spring.mail.properties.mail.smtp.from=${MAIL_USERNAME}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - APP_MAIL_NOREPLY=${MAIL_FROM_NOREPLY}
      - APP_MAIL_SUPPORT=${MAIL_FROM_SUPPORT}
      - APP_FRONTEND_URL=http://bauerblick.com
      - ALLOWED_ORIGIN=http://bauerblick.com
      - SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED=false

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  sensor-ingestion-service:
    build: ./backend/sensor-ingestion-service
    container_name: sensor-ingestion
    depends_on:
      rabbitmq:
        condition: service_healthy
      users-db:
        condition: service_started
      farms-db:
        condition: service_started
      rule-engine:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  frontend:
    build: ./frontend
    container_name: bauerblick-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api-gateway
volumes:
  users-db_data:
  farms-db_data:
  notifications-db_data:
